### ISSUE TITLE
Add Licence to clarify further use

### ISSUE THREAD

**Issue by Erikmitk** [bclin087/Simple-Code39-generator-for-iOS#1]
I was looking for a simple way to generate Code39 barcodes in an app and found your repo. It works great and I'd like to use it further.

The README states to copy the files and simply use them but the header of the files read `Copyright © 2015 Gemmy Planet, Inc. All rights reserved.`. So using them in a project is legally questionable for me. Although I suspect the licensing information is the one Xcode automatically generates for you.

To be on the safe side I'd encourage you to explicitly adopt a more generous license for your project. My suggestion would be to use MIT (https://opensource.org/licenses/MIT) if I had a choice.😊

**Comment by bclin087** [comment]
Glad to help, feel free to use! I’ll update the license :D

**Comment by bclin087** [comment]
Added LICENSE file (MIT License) and removed copyright in source files.
